player_settings:
  save_states:
    player_1:
    player_2:
    player_3:
    player_4: "/home/thomas/IdeaProjects/Biber/trained_players/epsilon-greedy.pkl"
  decision_logic:
    player_1: "random"
    player_2: "random"
    player_3: "random"
    player_4: "epsilon-greedy"
